name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run action
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: |
        # ml workflow
        pip install -r requirements.txt
        python train.py

        echo "MODEL METRICS"
        cat metrics.txt
